# documentation at: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: 'cargo'
    directory: '/src/main'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    milestone: 24 # "Code health and maintenance"
    labels:
      - 'Component: Build'

  - package-ecosystem: 'cargo'
    directory: '/src/test'
    schedule:
      interval: 'daily'
    target-branch: 'main'
    milestone: 24 # "Code health and maintenance"
    labels:
      - 'Component: Build'
