[package]
name = "shadow-rs"
version = "2.0.0-pre"
edition = "2018"
publish = false

[lib]
path = "lib.rs"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
rand = "0.7.3"

[build-dependencies]
