# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Lint Checks

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize]

jobs:

  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install flake8
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude src/external

  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
          echo "::add-path::$HOME/.cargo/bin"
      - name: Rustfmt check
        run: cd src && cargo fmt -- --check

  lint-bindings:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    env:
      CONTAINER: ubuntu:20.04
      CC: clang
      CXX: clang++
      BUILDTYPE: release
    steps:
      - uses: actions/checkout@master
      - name: Install deps
        run: |
          ci/container_scripts/install_deps.sh
          ci/container_scripts/install_extra_deps.sh
          echo "::add-path::$HOME/.cargo/bin"
      - name: Install Rust packages
        run: cargo install --force cbindgen bindgen
      - name: Check bindings
        run: |
          mv src/main/bindings/rust/wrapper.rs /tmp/main-bindings-rust.rs
          mv src/main/bindings/c/bindings.h /tmp/main-bindings-c.h
          mv src/support/logger/rust_bindings/src/bindings.rs /tmp/support-logger-rust.h
          mkdir build
          (cd build && cmake --target bindings .. && make bindings)
          diff src/main/bindings/rust/wrapper.rs /tmp/main-bindings-rust.rs
          diff src/main/bindings/c/bindings.h /tmp/main-bindings-c.h
          diff src/support/logger/rust_bindings/src/bindings.rs /tmp/support-logger-rust.h
