# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Lint Checks

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize]

jobs:

  lint-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install flake8
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude src/external

  lint-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Rustfmt check
        run: |
          (cd src/main && cargo fmt -- --check)
          (cd src/test && cargo fmt -- --check)
          (cd src/support/logger/rust_bindings && cargo fmt -- --check)

  lint-bindings:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    env:
      CONTAINER: ubuntu:20.04
      CC: clang
      CXX: clang++
      BUILDTYPE: release
      RUSTPROFILE: minimal
    steps:
      - name: Install git
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y git
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          ci/container_scripts/install_deps.sh
          ci/container_scripts/install_extra_deps.sh
          echo "::add-path::$HOME/.cargo/bin"
      - name: Install Rust packages
        run: |
          rustup component add rustfmt
          cargo install --force --version 0.15.0 cbindgen
          cargo install --force --version 0.55.1 bindgen
      - name: Check bindings
        run: |
          mkdir build
          cbindgen --version
          bindgen --version
          echo "If the bindings are different, you may want to check that your local cbindgen/bindgen versions match with the CI, and update the CI version numbers if necessary."
          (cd build && cmake --target bindings .. && make bindings)
          git diff --exit-code
