# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Shadow Tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize]

env:
  CARGO_TERM_COLOR: always

jobs:
  shadow:
    # there's only one job in the workflow, so we won't give it a name
    name: ' '
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      # the default for ubuntu:18.04, but with the size increased from 65536k
      options: '--shm-size="1g"'
    strategy:
      matrix:
        container: ['ubuntu:16.04', 'ubuntu:18.04', 'ubuntu:20.04', 'debian:10-slim', 'fedora:32', 'centos:7', 'centos:8']
        cc: ['gcc', 'clang']
        buildtype: ['debug', 'release']
        include:
          # Add a single configuration for testing the C syscall handlers
          - container: 'ubuntu:20.04'
            cc: 'clang'
            buildtype: 'use-c-syscalls'
    env:
      CC: ${{ matrix.cc }}
      CONTAINER: ${{ matrix.container }}
      BUILDTYPE: ${{ matrix.buildtype }}
      RUSTPROFILE: minimal

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          . ci/container_scripts/install_deps.sh
          . ci/container_scripts/install_extra_deps.sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build
        run: . ci/container_scripts/build_and_install.sh

      - name: Test
        run: . ci/container_scripts/test.sh

      - name: Upload shadow data directories
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: shadow-data-dirs
          path: build/**/*.data/*

      - name: Upload shadow log file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: shadow-log-file
          path: build/Testing/Temporary/*
